# Generated by Django 3.2 on 2021-04-07 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('TENTATIVE', 'Tentative'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='TENTATIVE', max_length=60)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_event', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('event_type', models.CharField(choices=[('other', 'Other'), ('general', 'General'), ('pto', 'Paid Time Off'), ('interview', 'Interview')], max_length=30)),
                ('dt_start', models.DateTimeField(help_text='Will store as UTC, set TZ on front end and process to UTC.')),
                ('dt_end', models.DateTimeField()),
                ('description', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=100)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('reminder', models.PositiveIntegerField(default=0)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('summary', models.CharField(max_length=250)),
                ('transparent', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('attendees', models.ManyToManyField(related_name='events', through='events.Attendees', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='attendees',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_event', to='events.calendarevent'),
        ),
    ]
