# Generated by Django 3.2 on 2021-04-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='dt_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='dt_start',
            field=models.DateField(help_text='Will store as UTC, set TZ on front end and process to UTC.'),
        ),
    ]
