# Generated by Django 3.2 on 2021-04-12 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210412_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='summary',
            new_name='notes',
        ),
    ]
